[package]
name = "pkg-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.35"
reqwest = { version = "0.12.9", features = ["blocking"] }
semver = "1.0.24"
serde = {version= "1.0.216", features = ["derive"]}
serde_json = "1.0.133"
serde_yaml = "0.9"
tar = "0.4.43"
